// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package catalogdb

import (
	"context"
)

// iteratorForInsertSeats implements pgx.CopyFromSource.
type iteratorForInsertSeats struct {
	rows                 []InsertSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EventID,
		r.rows[0].SeatID,
		r.rows[0].Zone,
		r.rows[0].RowLabel,
		r.rows[0].SeatNo,
		r.rows[0].PriceVnd,
	}, nil
}

func (r iteratorForInsertSeats) Err() error {
	return nil
}

func (q *Queries) InsertSeats(ctx context.Context, arg []InsertSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"seats"}, []string{"event_id", "seat_id", "zone", "row_label", "seat_no", "price_vnd"}, &iteratorForInsertSeats{rows: arg})
}
