// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"time"
)

type Event struct {
	ID               int64
	Name             string
	Venue            string
	StartsAt         time.Time
	SaleOpensAt      time.Time
	MaxSeatsPerOrder int32
}
