// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogdb

import (
	"context"

	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, venue, starts_at, sale_opens_at, max_seats_per_order)
VALUES (
  $1,
  $2,
  now() + $3::interval,
  now() + $4::interval,
  $5
)
RETURNING id
`

type CreateEventParams struct {
	Name             string
	Venue            string
	StartsIn         time.Duration
	SaleOpensIn      time.Duration
	MaxSeatsPerOrder int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Venue,
		arg.StartsIn,
		arg.SaleOpensIn,
		arg.MaxSeatsPerOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, venue, starts_at, sale_opens_at, max_seats_per_order
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.SaleOpensAt,
		&i.MaxSeatsPerOrder,
	)
	return i, err
}

type InsertSeatsParams struct {
	EventID  int64
	SeatID   string
	Zone     string
	RowLabel string
	SeatNo   int32
	PriceVnd int64
}

const isSaleOpen = `-- name: IsSaleOpen :one
SELECT sale_opens_at <= now() AS open
FROM events
WHERE id = $1
`

// Sale opening is a deadline decision, so it uses the database clock.
func (q *Queries) IsSaleOpen(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isSaleOpen, id)
	var open bool
	err := row.Scan(&open)
	return open, err
}

const listSeats = `-- name: ListSeats :many
SELECT seat_id, zone, row_label, seat_no, price_vnd
FROM seats
WHERE event_id = $1
ORDER BY price_vnd DESC, zone, length(row_label), row_label, seat_no
`

type ListSeatsRow struct {
	SeatID   string
	Zone     string
	RowLabel string
	SeatNo   int32
	PriceVnd int64
}

// Seats in display order: most expensive zone first, then row and seat number.
func (q *Queries) ListSeats(ctx context.Context, eventID int64) ([]ListSeatsRow, error) {
	rows, err := q.db.Query(ctx, listSeats, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsRow
	for rows.Next() {
		var i ListSeatsRow
		if err := rows.Scan(
			&i.SeatID,
			&i.Zone,
			&i.RowLabel,
			&i.SeatNo,
			&i.PriceVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
