// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO outbox (id, topic, msg_key, event_type, payload)
SELECT
  s.id,
  $1::text,
  $2::text,
  $3::text,
  $4::jsonb || jsonb_build_object(
    'event_id', s.id,
    'event_type', $3::text,
    'occurred_at', now()
  )
FROM (SELECT nextval(pg_get_serial_sequence('outbox', 'id')) AS id) AS s
RETURNING id
`

type InsertMessageParams struct {
	Topic     string
	MsgKey    string
	EventType string
	Payload   []byte
}

// The id is drawn first so the stored payload can carry it as event_id
// (consumers deduplicate on it). occurred_at uses the database clock.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.Topic,
		arg.MsgKey,
		arg.EventType,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
