// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package inventorydb

import (
	"context"

	"github.com/google/uuid"
	"time"
)

const countOrderTickets = `-- name: CountOrderTickets :one
SELECT count(*)
FROM tickets
WHERE event_id = $1::bigint
  AND seat_id = ANY($2::text[])
  AND order_id = $3::uuid
`

type CountOrderTicketsParams struct {
	EventID int64
	SeatIds []string
	OrderID uuid.UUID
}

func (q *Queries) CountOrderTickets(ctx context.Context, arg CountOrderTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderTickets, arg.EventID, arg.SeatIds, arg.OrderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHolds = `-- name: DeleteHolds :execrows
DELETE FROM seat_holds
WHERE event_id = $1::bigint
  AND seat_id = ANY($2::text[])
  AND order_id = $3::uuid
`

type DeleteHoldsParams struct {
	EventID int64
	SeatIds []string
	OrderID uuid.UUID
}

func (q *Queries) DeleteHolds(ctx context.Context, arg DeleteHoldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHolds, arg.EventID, arg.SeatIds, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockSeats = `-- name: LockSeats :many
SELECT seat_id
FROM seats
WHERE event_id = $1::bigint AND seat_id = ANY($2::text[])
ORDER BY seat_id
FOR UPDATE
`

type LockSeatsParams struct {
	EventID int64
	SeatIds []string
}

// Locks the requested seat rows in seat_id order so concurrent holds on
// overlapping seats always lock in the same order and cannot deadlock.
func (q *Queries) LockSeats(ctx context.Context, arg LockSeatsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, lockSeats, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var seat_id string
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seatStatuses = `-- name: SeatStatuses :many
SELECT seat_id, 'SOLD'::text AS status
FROM tickets
WHERE event_id = $1::bigint AND seat_id = ANY($2::text[])
UNION ALL
SELECT seat_id, 'HELD'::text AS status
FROM seat_holds
WHERE event_id = $1::bigint
  AND seat_id = ANY($2::text[])
  AND expires_at > now()
`

type SeatStatusesParams struct {
	EventID int64
	SeatIds []string
}

type SeatStatusesRow struct {
	SeatID string
	Status string
}

// Only seats that are not available; callers default the rest to AVAILABLE.
// A seat can appear twice (ticket plus stale hold); SOLD wins.
func (q *Queries) SeatStatuses(ctx context.Context, arg SeatStatusesParams) ([]SeatStatusesRow, error) {
	rows, err := q.db.Query(ctx, seatStatuses, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeatStatusesRow
	for rows.Next() {
		var i SeatStatusesRow
		if err := rows.Scan(&i.SeatID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takenSeats = `-- name: TakenSeats :many
SELECT seat_id
FROM seat_holds
WHERE event_id = $1::bigint
  AND seat_id = ANY($2::text[])
  AND expires_at > now()
  AND order_id <> $3::uuid
UNION
SELECT seat_id
FROM tickets
WHERE event_id = $1::bigint AND seat_id = ANY($2::text[])
ORDER BY seat_id
`

type TakenSeatsParams struct {
	EventID int64
	SeatIds []string
	OrderID uuid.UUID
}

// Seats held by another order (and not yet expired) or already ticketed.
// A hold by the same order does not count, which makes Hold idempotent.
func (q *Queries) TakenSeats(ctx context.Context, arg TakenSeatsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, takenSeats, arg.EventID, arg.SeatIds, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var seat_id string
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHolds = `-- name: UpsertHolds :exec
INSERT INTO seat_holds (event_id, seat_id, order_id, expires_at)
SELECT $1::bigint, s, $2::uuid, now() + $3::interval
FROM unnest($4::text[]) AS s
ON CONFLICT (event_id, seat_id) DO UPDATE
SET order_id = EXCLUDED.order_id,
    expires_at = EXCLUDED.expires_at
`

type UpsertHoldsParams struct {
	EventID int64
	OrderID uuid.UUID
	Ttl     time.Duration
	SeatIds []string
}

func (q *Queries) UpsertHolds(ctx context.Context, arg UpsertHoldsParams) error {
	_, err := q.db.Exec(ctx, upsertHolds,
		arg.EventID,
		arg.OrderID,
		arg.Ttl,
		arg.SeatIds,
	)
	return err
}
