// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package orderdb

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID             uuid.UUID
	EventID        int64
	UserID         int64
	Status         string
	TotalVnd       int64
	IdempotencyKey string
	RequestHash    string
	HoldExpiresAt  time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
