// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package orderdb

import (
	"context"

	"github.com/google/uuid"
	"time"
)

const expireDueOrders = `-- name: ExpireDueOrders :many
WITH due AS (
  SELECT id
  FROM orders
  WHERE status = 'HELD' AND hold_expires_at < now()
  ORDER BY hold_expires_at
  LIMIT $1::int
  FOR UPDATE SKIP LOCKED
)
UPDATE orders o
SET status = 'EXPIRED', updated_at = now()
FROM due
WHERE o.id = due.id AND o.status = 'HELD'
RETURNING o.id, o.event_id, o.user_id, o.total_vnd
`

type ExpireDueOrdersRow struct {
	ID       uuid.UUID
	EventID  int64
	UserID   int64
	TotalVnd int64
}

// Moves up to batch_size HELD orders whose hold has passed (database clock)
// to EXPIRED (SPEC.md 9.4). SKIP LOCKED lets several workers run side by
// side and skips orders locked by a concurrent cancel or payment.
func (q *Queries) ExpireDueOrders(ctx context.Context, batchSize int32) ([]ExpireDueOrdersRow, error) {
	rows, err := q.db.Query(ctx, expireDueOrders, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireDueOrdersRow
	for rows.Next() {
		var i ExpireDueOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.TotalVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.TotalVnd,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.HoldExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByKey = `-- name: GetOrderByKey :one
SELECT id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at, created_at, updated_at FROM orders
WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByKeyParams struct {
	UserID         int64
	IdempotencyKey string
}

func (q *Queries) GetOrderByKey(ctx context.Context, arg GetOrderByKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByKey, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.TotalVnd,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.HoldExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at, created_at, updated_at FROM orders WHERE id = $1
FOR UPDATE
`

// Locks the order row so its status cannot change until the transaction ends.
func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.TotalVnd,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.HoldExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHeldOrder = `-- name: InsertHeldOrder :one
INSERT INTO orders (id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at)
VALUES (
  $1,
  $2,
  $3,
  'HELD',
  $4,
  $5,
  $6,
  now() + $7::interval
)
RETURNING id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at, created_at, updated_at
`

type InsertHeldOrderParams struct {
	OrderID        uuid.UUID
	EventID        int64
	UserID         int64
	TotalVnd       int64
	IdempotencyKey string
	RequestHash    string
	HoldTtl        time.Duration
}

func (q *Queries) InsertHeldOrder(ctx context.Context, arg InsertHeldOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertHeldOrder,
		arg.OrderID,
		arg.EventID,
		arg.UserID,
		arg.TotalVnd,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.HoldTtl,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.TotalVnd,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.HoldExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderSeats = `-- name: InsertOrderSeats :exec
INSERT INTO order_seats (order_id, event_id, seat_id, price_vnd)
SELECT $1::uuid, $2::bigint, unnest($3::text[]), unnest($4::bigint[])
`

type InsertOrderSeatsParams struct {
	OrderID uuid.UUID
	EventID int64
	SeatIds []string
	Prices  []int64
}

// seat_ids and prices have the same length; the two unnests are zipped.
func (q *Queries) InsertOrderSeats(ctx context.Context, arg InsertOrderSeatsParams) error {
	_, err := q.db.Exec(ctx, insertOrderSeats,
		arg.OrderID,
		arg.EventID,
		arg.SeatIds,
		arg.Prices,
	)
	return err
}

const listOrderSeats = `-- name: ListOrderSeats :many
SELECT seat_id, price_vnd
FROM order_seats
WHERE order_id = $1
ORDER BY seat_id
`

type ListOrderSeatsRow struct {
	SeatID   string
	PriceVnd int64
}

func (q *Queries) ListOrderSeats(ctx context.Context, orderID uuid.UUID) ([]ListOrderSeatsRow, error) {
	rows, err := q.db.Query(ctx, listOrderSeats, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderSeatsRow
	for rows.Next() {
		var i ListOrderSeatsRow
		if err := rows.Scan(&i.SeatID, &i.PriceVnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsOfOrders = `-- name: ListSeatsOfOrders :many
SELECT order_id, seat_id, price_vnd
FROM order_seats
WHERE order_id = ANY($1::uuid[])
ORDER BY order_id, seat_id
`

type ListSeatsOfOrdersRow struct {
	OrderID  uuid.UUID
	SeatID   string
	PriceVnd int64
}

func (q *Queries) ListSeatsOfOrders(ctx context.Context, orderIds []uuid.UUID) ([]ListSeatsOfOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSeatsOfOrders, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsOfOrdersRow
	for rows.Next() {
		var i ListSeatsOfOrdersRow
		if err := rows.Scan(&i.OrderID, &i.SeatID, &i.PriceVnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionOrder = `-- name: TransitionOrder :one
UPDATE orders
SET status = $1, updated_at = now()
WHERE id = $2 AND status = $3
RETURNING id, event_id, user_id, status, total_vnd, idempotency_key, request_hash, hold_expires_at, created_at, updated_at
`

type TransitionOrderParams struct {
	ToStatus   string
	OrderID    uuid.UUID
	FromStatus string
}

// Every status change goes through this conditional update. Zero rows means
// the order was not in from_status; the caller re-reads and decides.
func (q *Queries) TransitionOrder(ctx context.Context, arg TransitionOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, transitionOrder, arg.ToStatus, arg.OrderID, arg.FromStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.TotalVnd,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.HoldExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
