// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
)

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id) VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, ensureUser, id)
	return err
}
